# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubetui < Formula
  desc "A terminal UI for managing and monitoring Kubernetes clusters"
  homepage "https://github.com/14f3v/kubectl-tui"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v1.0.0/kubetui_1.0.0_darwin_amd64.tar.gz"
      sha256 "185fcdf398137b875a7a1227babce8bcda3b0b3f827cd05fd9516eec81ce96a6"

      define_method(:install) do
        bin.install "kubetui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v1.0.0/kubetui_1.0.0_darwin_arm64.tar.gz"
      sha256 "b5225c32f780b2bcef85bfaa8b254395e19eea2019996676df82c9d849a1ace6"

      define_method(:install) do
        bin.install "kubetui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v1.0.0/kubetui_1.0.0_linux_amd64.tar.gz"
      sha256 "52c53541d8ec663c92496ac0c4781ab7170cdf7acb3902b41632cbe1bd04efa8"
      define_method(:install) do
        bin.install "kubetui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v1.0.0/kubetui_1.0.0_linux_arm64.tar.gz"
      sha256 "30b4a90e4db0775115c5ce849b853a036acf98a585eba4a03456142e17d9c7e9"
      define_method(:install) do
        bin.install "kubetui"
      end
    end
  end

  test do
    system "#{bin}/kubetui", "--version"
  end
end
