# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlTui < Formula
  desc "A terminal UI for managing and monitoring Kubernetes clusters"
  homepage "https://github.com/14f3v/kubectl-tui"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v0.1.2/kubetui_0.1.2_darwin_amd64.tar.gz"
      sha256 "ac45e7d1706e8874032d2845052aa51e0f5dd58d87f944be31f026459d61c3a0"

      define_method(:install) do
        bin.install "kubetui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v0.1.2/kubetui_0.1.2_darwin_arm64.tar.gz"
      sha256 "e0a454fbe450e3d9d81d81c862635ff11d71fd9c25323f29599f5206dd3c77a1"

      define_method(:install) do
        bin.install "kubetui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v0.1.2/kubetui_0.1.2_linux_amd64.tar.gz"
      sha256 "71f4fbd51ba7892693d9ad43ae6d7dcb469671a963660466fc4462bd9bf23c94"
      define_method(:install) do
        bin.install "kubetui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v0.1.2/kubetui_0.1.2_linux_arm64.tar.gz"
      sha256 "b077f38c9b7a2103073b1637e5bd15ed4f842f6c1cc8c6cd2bd507a3559d4c3a"
      define_method(:install) do
        bin.install "kubetui"
      end
    end
  end

  test do
    system "#{bin}/kubetui", "--version"
  end
end
