# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubetui < Formula
  desc "A terminal UI for managing and monitoring Kubernetes clusters"
  homepage "https://github.com/14f3v/kubectl-tui"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v0.1.3/kubetui_0.1.3_darwin_amd64.tar.gz"
      sha256 "0a56780c66778ca325022b4c20843f2405aaa2b7b6015f94e0060bb0d6f39bdc"

      define_method(:install) do
        bin.install "kubetui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v0.1.3/kubetui_0.1.3_darwin_arm64.tar.gz"
      sha256 "67a7aec6009811aebe0dc5735c18bf50c88a2c11a8e41075d4e0892cbf9d82d6"

      define_method(:install) do
        bin.install "kubetui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v0.1.3/kubetui_0.1.3_linux_amd64.tar.gz"
      sha256 "76cf1d0a67bc90437ed4ec0e4b1dd5de38cc5556e8902f136dbec360c103b192"
      define_method(:install) do
        bin.install "kubetui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/14f3v/kubectl-tui/releases/download/v0.1.3/kubetui_0.1.3_linux_arm64.tar.gz"
      sha256 "ca40d947be7b8fd18fee688b431af034fc26bae9684e802db9d55b275528fe95"
      define_method(:install) do
        bin.install "kubetui"
      end
    end
  end

  test do
    system "#{bin}/kubetui", "--version"
  end
end
